import type { Metadata, Viewport } from "next";
import "./globals.css";
import site from "@/site.config";
import { themeToCssVars } from "@/lib/theme";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

/**
 * Root layout. Brand styling is injected as CSS variables on <html> from
 * site.config.ts, so swapping the config re-skins the entire app.
 */
export const metadata: Metadata = {
  metadataBase: new URL(site.company.url),
  title: {
    default: site.seo.defaultTitle,
    template: site.seo.titleTemplate,
  },
  description: site.seo.defaultDescription,
  applicationName: site.company.name,
  openGraph: {
    type: "website",
    locale: site.seo.locale,
    siteName: site.company.name,
    title: site.seo.defaultTitle,
    description: site.seo.defaultDescription,
    // OG image is generated by src/app/opengraph-image.tsx (file convention),
    // so it's always brand-correct. Twitter cards fall back to the OG image.
  },
  twitter: {
    card: "summary_large_image",
    title: site.seo.defaultTitle,
    description: site.seo.defaultDescription,
    ...(site.seo.twitterHandle ? { site: site.seo.twitterHandle } : {}),
  },
  alternates: { canonical: "/" },
};

export const viewport: Viewport = {
  themeColor: `rgb(${site.theme.colors.brand})`,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const cssVars = themeToCssVars(site.theme) as React.CSSProperties;

  return (
    <html lang={site.seo.locale.split("_")[0]} style={cssVars}>
      <body className="flex min-h-screen flex-col">
        {/* Skip link for keyboard / screen-reader users. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-50 btn-primary"
        >
          Skip to content
        </a>
        <Header />
        <main id="main" className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
